### PR TITLE
Named Branch

### PR DESCRIPTION
**Pull request by DerekPeacock**
I have changed the name to student name

### CODE REVIEW

**Comment by kabdala** [comment]
Hence there has no one else, has created or help excepting you and it’s my
primary email, dear you did not feedback me on Apps05
Best wishes
Khayre
To

**Comment by kabdala** [comment]
Respected Derek,
My App05 is updated on the github. But on the blackboard there is not any
option to share the link of github. There is only option where the App01 to
App04 was uploaded.  So please guide me where i can share the link of
github on blackboard. So that u can review my progress on Appo5
I will be thankful to you.
Best regards
Khayre

**Comment by DerekPeacock** [comment]
Hi Khayre
It is not important as I have a link to your Repository in the spreadsheet.  I will be marking it tomorrow.  I can see that you last changed it 4 days ago
bye for nowDerek

    On Saturday, December 5, 2020, 11:13:43 AM GMT, Khayre Abdala <notifications@github.com> wrote:  
 
 

Respected Derek,
My App05 is updated on the github. But on the blackboard there is not any
option to share the link of github. There is only option where the App01 to
App04 was uploaded. So please guide me where i can share the link of
github on blackboard. So that u can review my progress on Appo5
I will be thankful to you.
Best regards
Khayre

**Comment by DerekPeacock** [comment]
Hi Khayre
You have complete almost all the functionality, but there is no testing and no wiki page so your overall mark for App05 is only 36%
Surely it is worth doing the testing to raise this mark?


You only have 22% for the whole module so you are in danger of failing this module.  Please arrange a 1:1 online meeting with me so that I can help you raise these marks
best wishesDerek
    On Saturday, December 5, 2020, 11:13:43 AM GMT, Khayre Abdala <notifications@github.com> wrote:  
 
 

Respected Derek,
My App05 is updated on the github. But on the blackboard there is not any
option to share the link of github. There is only option where the App01 to
App04 was uploaded. So please guide me where i can share the link of
github on blackboard. So that u can review my progress on Appo5
I will be thankful to you.
Best regards
Khayre

**Pull request merged**
